{
 "title": "Errors",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Users",
    "query": {}
   },
   {
    "name": "Errors",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Errors by user",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "averageAbove(aliasByNode(sortByTotal(errors.$Users.$Errors.count), 1, 2), 0)"
    }
   ]
  },
  {
   "title": "Errors globally",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "averageAbove(groupByNode(errors.*.*.count, 2, 'sumSeries'), 0)"
    }
   ]
  },
  {
   "title": "Unique erors by user",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "averageAbove(groupByNode(errors.*.*.count, 1, 'countSeries'), 0)"
    }
   ]
  }
 ]
}