version: "3"

x-logging: &default-logging
  driver: "local"
  options:
    max-size: "50m"
    max-file: "1"

services:
  nodejs:
    build: .
    restart: unless-stopped
    environment:
      - ENVIRONMENT=docker
    ports:
      - 10002:10002
    volumes:
      - ./logs:/usr/ErrorExporter/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging: *default-logging
